/*
	Civilization
	Credits: ChimpanG
*/

-----------------------------------------------
-- Types
-----------------------------------------------

INSERT INTO	Types
		(Type,								Kind					)
VALUES	('CIVILIZATION_CVS_PHILIPPINES',	'KIND_CIVILIZATION'		);
		
-----------------------------------------------
-- Civilizations
-----------------------------------------------

INSERT INTO	Civilizations
		(CivilizationType,					Name,										Description,										Adjective,										StartingCivilizationLevelType,		RandomCityNameDepth,	Ethnicity			)
VALUES	('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CIVILIZATION_CVS_PHILIPPINES_NAME',	'LOC_CIVILIZATION_CVS_PHILIPPINES_DESCRIPTION',		'LOC_CIVILIZATION_CVS_PHILIPPINES_ADJECTIVE',	'CIVILIZATION_LEVEL_FULL_CIV',		20,						'ETHNICITY_ASIAN' 	);
		
-----------------------------------------------
-- CityNames
-----------------------------------------------

INSERT INTO	CityNames
		(CivilizationType,					CityName								)						
VALUES	('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_SC_QUEZON'				),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_SC_DAVAO'				),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_SC_CALOOCAN'				),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_SC_CEBU'					),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_SC_ZAMBOANGA'			),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_SC_TAGUIG'				),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_SC_ANTIPOLO'				),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_SC_PASIG'				),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_SC_CAGAYAN'				),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_SC_PARANQUE'				),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_SC_DASMARINAS'			),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_SC_VALENZUELA'			),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_SC_BACOOR'				),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_SC_MACTAN'				),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_SC_LAS_PINAS'			),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_SC_PUERTO_PRINCESA'		),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_SC_COTABATO'				),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_SC_NAGA'					),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_SC_ILOILO'				),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_SC_BUTUAN'				),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_SC_TONDO'				),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_SC_ROXAS'				),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_SC_MAKATI'				),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_SC_SAN_JOSE_DEL_MONTE'	),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_SC_BACOLOD'				),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_SC_MUNTINLUPA'			),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_SC_CALAMBA'				),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_SC_MARIKINA'				),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_SC_PASAY'				),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_SC_ANGELES'				),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_SC_IMUS'					),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_SC_MANDALUYONG'			),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_SC_MALABON'				),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_SC_MANDAUE'				),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_SC_SANTA_ROSA'			),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_SC_BAGUIO'				),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_SC_ILIGAN'				),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_SC_TARLAC'				),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_SC_BINAN'				),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_SC_LIPA'					),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_SC_BATANGAS'				),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_SC_SAN_PEDRO'			),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_SC_CABUYAO'				),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_SC_SAN_FERNANDO'			),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_SC_CABANATUAN'			),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_SC_LUCENA'				),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_SC_SAN_PABLO'			),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_SC_TAGUM'				),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_SC_MALOLOS'				),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_SC_MABALACAT'			),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_SC_NAVOTAS'				),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_SC_TACLOBAN'				),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_SC_OLONGAPO'				),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_SC_TALISAY'				),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_SC_ORMOC'				),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_SC_MEYCAUAYAN'			),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_SC_MARAWI'				),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_SC_PAGADIAN'				),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_SC_LEGAZPI'				),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_SC_PANABO'				),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_SC_CALBAYOG'				),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_SC_KABANKALAN'			),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_SC_KORONADAL'			),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_SC_MALAYBALAY'			),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_SC_TANAUAN'				),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_SC_DAGUPAN'				),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_SC_BAGO'					),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_SC_DIGOS'				),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_SC_SORSOGON'				);
		
-----------------------------------------------
-- CivilizationCitizenNames
-----------------------------------------------

INSERT INTO	CivilizationCitizenNames
		(CivilizationType,						CitizenName,								Female	)
VALUES	('CIVILIZATION_CVS_PHILIPPINES',		'LOC_CITIZEN_CVS_PHILIPPINES_MALE_1',		0 		),
		('CIVILIZATION_CVS_PHILIPPINES',		'LOC_CITIZEN_CVS_PHILIPPINES_MALE_2',		0 		),
		('CIVILIZATION_CVS_PHILIPPINES',		'LOC_CITIZEN_CVS_PHILIPPINES_MALE_3',		0 		),
		('CIVILIZATION_CVS_PHILIPPINES',		'LOC_CITIZEN_CVS_PHILIPPINES_MALE_4',		0 		),
		('CIVILIZATION_CVS_PHILIPPINES',		'LOC_CITIZEN_CVS_PHILIPPINES_MALE_5',		0 		),
		('CIVILIZATION_CVS_PHILIPPINES',		'LOC_CITIZEN_CVS_PHILIPPINES_MALE_6',		0 		),
		('CIVILIZATION_CVS_PHILIPPINES',		'LOC_CITIZEN_CVS_PHILIPPINES_MALE_7',		0 		),
		('CIVILIZATION_CVS_PHILIPPINES',		'LOC_CITIZEN_CVS_PHILIPPINES_MALE_8',		0 		),
		('CIVILIZATION_CVS_PHILIPPINES',		'LOC_CITIZEN_CVS_PHILIPPINES_MALE_9',		0 		),
		('CIVILIZATION_CVS_PHILIPPINES',		'LOC_CITIZEN_CVS_PHILIPPINES_MALE_10',		0 		),
		('CIVILIZATION_CVS_PHILIPPINES',		'LOC_CITIZEN_CVS_PHILIPPINES_FEMALE_1',		1 		),
		('CIVILIZATION_CVS_PHILIPPINES',		'LOC_CITIZEN_CVS_PHILIPPINES_FEMALE_2',		1 		),
		('CIVILIZATION_CVS_PHILIPPINES',		'LOC_CITIZEN_CVS_PHILIPPINES_FEMALE_3',		1 		),
		('CIVILIZATION_CVS_PHILIPPINES',		'LOC_CITIZEN_CVS_PHILIPPINES_FEMALE_4',		1 		),
		('CIVILIZATION_CVS_PHILIPPINES',		'LOC_CITIZEN_CVS_PHILIPPINES_FEMALE_5',		1 		),
		('CIVILIZATION_CVS_PHILIPPINES',		'LOC_CITIZEN_CVS_PHILIPPINES_FEMALE_6',		1 		),
		('CIVILIZATION_CVS_PHILIPPINES',		'LOC_CITIZEN_CVS_PHILIPPINES_FEMALE_7',		1 		),
		('CIVILIZATION_CVS_PHILIPPINES',		'LOC_CITIZEN_CVS_PHILIPPINES_FEMALE_8',		1 		),
		('CIVILIZATION_CVS_PHILIPPINES',		'LOC_CITIZEN_CVS_PHILIPPINES_FEMALE_9',		1 		),
		('CIVILIZATION_CVS_PHILIPPINES',		'LOC_CITIZEN_CVS_PHILIPPINES_FEMALE_10',	1 		);

-----------------------------------------------
-- CivilizationInfo
-----------------------------------------------

INSERT INTO	CivilizationInfo
		(CivilizationType,						Header,							Caption,									SortIndex	)
VALUES	('CIVILIZATION_CVS_PHILIPPINES',		'LOC_CIVINFO_LOCATION',			'LOC_CIVINFO_CVS_PHILIPPINES_LOCATION',		10			),
		('CIVILIZATION_CVS_PHILIPPINES',		'LOC_CIVINFO_SIZE',				'LOC_CIVINFO_CVS_PHILIPPINES_SIZE',			20			),
		('CIVILIZATION_CVS_PHILIPPINES',		'LOC_CIVINFO_POPULATION',		'LOC_CIVINFO_CVS_PHILIPPINES_POPULATION',	30			),
		('CIVILIZATION_CVS_PHILIPPINES',		'LOC_CIVINFO_CAPITAL',			'LOC_CIVINFO_CVS_PHILIPPINES_CAPITAL',		40			);
		
-----------------------------------------------
-- Start Bias
-----------------------------------------------

INSERT INTO	StartBiasFeatures
		(CivilizationType,					FeatureType,		 	Tier	)
VALUES	('CIVILIZATION_CVS_PHILIPPINES',	'FEATURE_JUNGLE',		3		);

INSERT INTO	StartBiasTerrains
		(CivilizationType,					TerrainType,		 	Tier	)
VALUES	('CIVILIZATION_CVS_PHILIPPINES',	'TERRAIN_COAST',		2		);