/*
	Strategy
	Credits: ChimpanG
*/

-- This file is not loaded in the database. It is to be used as a base for individual leader strategies.
		
-----------------------------------------------
-- AiFavoredItems
-----------------------------------------------

INSERT INTO AiFavoredItems
		(ListType,								Item,									Favored	)
VALUES  -- TECHS
		('LEADER_CVS_PLACEHOLDER_TECHS',		'TECH_CURRENCY',						1		),
		('LEADER_CVS_PLACEHOLDER_TECHS',		'TECH_SHIPBUILDING',					1		),
		('LEADER_CVS_PLACEHOLDER_TECHS',		'TECH_CELESTIAL_NAVIGATION',			1		),
		('LEADER_CVS_PLACEHOLDER_TECHS',		'TECH_CARTOGRAPHY',						1		),
		('LEADER_CVS_PLACEHOLDER_TECHS',		'TECH_SQUARE_RIGGING',					1		),
		('LEADER_CVS_PLACEHOLDER_TECHS',		'TECH_BANKING',							1		),
		('LEADER_CVS_PLACEHOLDER_TECHS',		'TECH_ECONOMICS',						1		),
		-- CIVICS
		('LEADER_CVS_PLACEHOLDER_CIVICS',		'CIVIC_FOREIGN_TRADE',					1		),
		('LEADER_CVS_PLACEHOLDER_CIVICS',		'CIVIC_EXPLORATION',					1		),
		('LEADER_CVS_PLACEHOLDER_CIVICS',		'CIVIC_GUILDS',							1		),
		-- DISTRICTS
		('LEADER_CVS_PLACEHOLDER_DISTRICTS',	'DISTRICT_COMMERCIAL_HUB',				1		),
		('LEADER_CVS_PLACEHOLDER_DISTRICTS',	'DISTRICT_HARBOR',						1		),
		-- BUILDINGS
		('LEADER_CVS_PLACEHOLDER_BUILDINGS',	'BUILDING_CVS_PHILIPPINES_UI',			1		),
		('LEADER_CVS_PLACEHOLDER_BUILDINGS',	'BUILDING_BANK',						1		),
		('LEADER_CVS_PLACEHOLDER_BUILDINGS',	'BUILDING_STOCK_EXCHANGE',				1		),
		('LEADER_CVS_PLACEHOLDER_BUILDINGS',	'BUILDING_LIGHTHOUSE',					1		),
		('LEADER_CVS_PLACEHOLDER_BUILDINGS',	'BUILDING_SHIPYARD',					1		),
		('LEADER_CVS_PLACEHOLDER_BUILDINGS',	'BUILDING_SEAPORT',						1		),
		-- WONDERS
		('LEADER_CVS_PLACEHOLDER_BUILDINGS',	'BUILDING_BIG_BEN',						1		),
		('LEADER_CVS_PLACEHOLDER_BUILDINGS',	'BUILDING_COLOSSUS',					1		),
		('LEADER_CVS_PLACEHOLDER_BUILDINGS',	'BUILDING_EIFFEL_TOWER',				1		),
		('LEADER_CVS_PLACEHOLDER_BUILDINGS',	'BUILDING_GREAT_LIGHTHOUSE',			1		),
		('LEADER_CVS_PLACEHOLDER_BUILDINGS',	'BUILDING_GREAT_ZIMBABWE',				1		),
		('LEADER_CVS_PLACEHOLDER_BUILDINGS',	'BUILDING_VENETIAN_ARSENAL',			1		),
		-- PROJECTS
		-- TACTICS
		-- DIPLOMACY
		('LEADER_CVS_PLACEHOLDER_DIPLOMACY',	'DIPLOACTION_PROPOSE_TRADE',			1		);

INSERT INTO AiFavoredItems
		(ListType,								Item,								Favored,	Value,	StringVal				)
VALUES  -- EXPANSION
		('LEADER_CVS_PLACEHOLDER_EXPANSION',	'Coastal',							1,			15,		NULL					),
		('LEADER_CVS_PLACEHOLDER_EXPANSION',	'Resource Class',					1,			5,		'RESOURCECLASS_BONUS'	),
		('LEADER_CVS_PLACEHOLDER_EXPANSION',	'Resource Class',					1,			5,		'RESOURCECLASS_LUXURY'	),
		('LEADER_CVS_PLACEHOLDER_EXPANSION',	'New Resources',					1,			15,		NULL					),
		('LEADER_CVS_PLACEHOLDER_EXPANSION',	'Specific Feature',					1,			5,		'FEATURE_CLIFFS_DOVER'	),
		('LEADER_CVS_PLACEHOLDER_EXPANSION',	'Specific Feature',					1,			5,		'FEATURE_PIOPIOTAHI'	),
		-- PSUEDOS
		('LEADER_CVS_PLACEHOLDER_PSUEDOS',		'PSEUDOYIELD_UNIT_TRADE',			1,			5,		NULL					),
		('LEADER_CVS_PLACEHOLDER_PSUEDOS',		'PSEUDOYIELD_GPP_MERCHANT',			1,			50,		NULL					),
		('LEADER_CVS_PLACEHOLDER_PSUEDOS',		'PSEUDOYIELD_GPP_ADMIRAL',			1,			30,		NULL					),
		('LEADER_CVS_PLACEHOLDER_PSUEDOS',		'PSEUDOYIELD_UNIT_NAVAL_COMBAT',	1,			30,		NULL					);
