/*
	Mod Support RwF Localisation
	Credits: ChimpanG
*/

-----------------------------------------------
-- Types
-----------------------------------------------

INSERT OR REPLACE INTO LocalizedText
		(Tag,																				Language,	Text						)
VALUES	("LOC_CIVILIZATION_CVS_PHILIPPINES_DESCRIPTION_JFD_CIVILIZATION",					"en_US",	"Filipino Civilization"		),

		("LOC_GOVERNMENT_JFD_CHIEFDOM_LEADER_TITLE_CVS_PHILIPPINES",						"en_US",	"Chief"						),
		("LOC_GOVERNMENT_JFD_CHIEFDOM_LEADER_TITLE_CVS_PHILIPPINES_FEMININE",				"en_US",	"Chief"						),
		("LOC_GOVERNMENT_JFD_HORDE_LEADER_TITLE_CVS_PHILIPPINES",							"en_US",	"Senapati"					),
		("LOC_GOVERNMENT_JFD_HORDE_LEADER_TITLE_CVS_PHILIPPINES_FEMININE",					"en_US",	"Senapati"					),
		("LOC_GOVERNMENT_JFD_POLIS_LEADER_TITLE_CVS_PHILIPPINES",							"en_US",	"Kumara"					),
		("LOC_GOVERNMENT_JFD_POLIS_LEADER_TITLE_CVS_PHILIPPINES_FEMININE",					"en_US",	"Kumari"					),

		("LOC_GOVERNMENT_JFD_AUTOCRACY_LEADER_TITLE_CVS_PHILIPPINES",						"en_US",	"Matran"					),
		("LOC_GOVERNMENT_JFD_AUTOCRACY_LEADER_TITLE_CVS_PHILIPPINES_FEMININE",				"en_US",	"Matran"					),
		("LOC_GOVERNMENT_JFD_OLIGARCHY_LEADER_TITLE_CVS_PHILIPPINES",						"en_US",	"Datuk"						),
		("LOC_GOVERNMENT_JFD_OLIGARCHY_LEADER_TITLE_CVS_PHILIPPINES_FEMININE",				"en_US",	"Datuk"						),
		("LOC_GOVERNMENT_JFD_CLASSICAL_DEMOCRACY_LEADER_TITLE_CVS_PHILIPPINES",				"en_US",	"Speaker"					),
		("LOC_GOVERNMENT_JFD_CLASSICAL_DEMOCRACY_LEADER_TITLE_CVS_PHILIPPINES_FEMININE",	"en_US",	"Speaker"					),

		("LOC_GOVERNMENT_JFD_FEUDAL_MONARCHY_LEADER_TITLE_CVS_PHILIPPINES",					"en_US",	"Raja"						),
		("LOC_GOVERNMENT_JFD_FEUDAL_MONARCHY_LEADER_TITLE_CVS_PHILIPPINES_FEMININE",		"en_US",	"Rani"						),
		("LOC_GOVERNMENT_JFD_MERCHANT_REPUBLIC_LEADER_TITLE_CVS_PHILIPPINES",				"en_US",	"Councillor"				),
		("LOC_GOVERNMENT_JFD_MERCHANT_REPUBLIC_LEADER_TITLE_CVS_PHILIPPINES_FEMININE",		"en_US",	"Councillor"				),
		("LOC_GOVERNMENT_JFD_GOVERNMENT_THEOCRACY_LEADER_TITLE_CVS_PHILIPPINES",			"en_US",	"Sultan"					),
		("LOC_GOVERNMENT_JFD_GOVERNMENT_THEOCRACY_LEADER_TITLE_CVS_PHILIPPINES_FEMININE",	"en_US",	"Sultan"					),

		("LOC_GOVERNMENT_JFD_MONARCHY_LEADER_TITLE_CVS_PHILIPPINES",						"en_US",	"Maharaja"					),
		("LOC_GOVERNMENT_JFD_MONARCHY_LEADER_TITLE_CVS_PHILIPPINES_FEMININE",				"en_US",	"Maharani"					),
		("LOC_GOVERNMENT_JFD_NOBLE_REPUBLIC_LEADER_TITLE_CVS_PHILIPPINES",					"en_US",	"Bhre"						),
		("LOC_GOVERNMENT_JFD_NOBLE_REPUBLIC_LEADER_TITLE_CVS_PHILIPPINES_FEMININE",			"en_US",	"Bhre"						),
		
		("LOC_GOVERNMENT_JFD_LIBERAL_DEMOCRACY_LEADER_TITLE_CVS_PHILIPPINES",				"en_US",	"President"					),
		("LOC_GOVERNMENT_JFD_LIBERAL_DEMOCRACY_LEADER_TITLE_CVS_PHILIPPINES_FEMININE",		"en_US",	"President"					),
		("LOC_GOVERNMENT_JFD_PEOPLES_REPUBLIC_LEADER_TITLE_CVS_PHILIPPINES",				"en_US",	"Chairman"					),
		("LOC_GOVERNMENT_JFD_PEOPLES_REPUBLIC_LEADER_TITLE_CVS_PHILIPPINES_FEMININE",		"en_US",	"Chairman"					),
		("LOC_GOVERNMENT_JFD_MILITARY_GUARDIANSHIP_LEADER_TITLE_CVS_PHILIPPINES",			"en_US",	"Jenderal Besar"			),
		("LOC_GOVERNMENT_JFD_MILITARY_GUARDIANSHIP_LEADER_TITLE_CVS_PHILIPPINES_FEMININE",	"en_US",	"Jenderal Besar"			),
		
		("LOC_GOVERNMENT_JFD_EMPIRE_LEADER_TITLE_CVS_PHILIPPINES",							"en_US",	"Chakkraphat"				),
		("LOC_GOVERNMENT_JFD_EMPIRE_LEADER_TITLE_CVS_PHILIPPINES_FEMININE",					"en_US",	"Chakkraphat"				);